### ISSUE TITLE
I have to type in my passcode whenever I start the terminal

### ISSUE THREAD

**Issue by caniko** [Grokon/ssh-agent.fish#1]
Is there any way to avoid having to type in my key passphrase every time I launch the terminal?

**Comment by sergio-lb** [comment]
On MacOS, you can use Keychain. On other systems, you need to save your password to a file or a variable and  load from them. You can also try 1pass cli or 1pass ssh agent If you use 1password.
I use WSL, so when I start the terminal for the first time, I enter my password and then it is not asked again until I reboot.

**Comment by caniko** [comment]
I guess this one is not for me, found another one that "just works" for me. Thanks for the info :)
